version: "3.9"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=old_red_lion
      - POSTGRES_PASSWORD=old_red_lion
      - POSTGRES_DB=old_red_lion_dev
    env_file:
      - ./.env.dev
volumes:
  postgres_data:
